#实例名
spring:
  application:
    name: nacos-discovery-consumer
  cloud:
  #注册中心
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        # 元数据
        metadata:
          name: consumer
#端口号
server:
  port: 8080

#开启 hystrix 熔断
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    enabled: true

#设置日志级别
logging:
  level:
    com:
      hss: info