spring:
  application:
    name: nacos-discovery-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        #n元数据
        metadata:
          name: gateway
    gateway:
      routes:
        - id: nacos-discovery-provider
          uri: lb://nacos-discovery-provider
          predicates:
            - Path=/provider/**
#            - Path=/demo
          filters:
            # 过滤掉路径中第一个
            - StripPrefix=1

server:
  port: 8054
