server:
  port: 8010
spring:
  application:
    name: biz-service
  datasource:
      url: jdbc:mysql://localhost:3306/alibaba-cloud-order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver